project_id = "xpmhahyvtyvrxryrqane"

[functions.seed-resume-templates]
verify_jwt = false

[functions.interview-feedback]
verify_jwt = false

[functions.generate-cover-letter]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false

[functions.send-subscription-update]
verify_jwt = false

[functions.send-contact-form]
verify_jwt = false

[functions.seed-subscription-plans]
verify_jwt = false

[functions.search-jobs]
verify_jwt = false

[functions.generate-resume-content]
verify_jwt = false

[functions.update-tech-templates]
verify_jwt = false

[functions.analyze-resume-ats]
verify_jwt = false

[functions.analyze-skill-gap]
verify_jwt = false

[functions.analyze-resume-match]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.rewrite-bullet]
verify_jwt = false

[functions.parse-resume-file]
verify_jwt = false

[functions.vaylance-chat]
verify_jwt = false

[functions.parse-resume-ai]
verify_jwt = false
