project_id = "xpmhahyvtyvrxryrqane"

[functions.create-checkout]
verify_jwt = true

[functions.seed-resume-templates]
verify_jwt = false

[functions.interview-feedback]
verify_jwt = false

[functions.generate-cover-letter]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false

[functions.send-subscription-update]
verify_jwt = false

[functions.send-contact-form]
verify_jwt = false

[functions.lemon-squeezy-webhook]
verify_jwt = false

[functions.seed-subscription-plans]
verify_jwt = false
